development:
  adapter: postgresql
  database: my_database_development
  pool: 5
  timeout: 5000
  template: template0
  
test:
  adapter: postgresql
  database: my_database_test
  pool: 5
  timeout: 5000
  template: template0

production:
  adapter: postgresql
  database: my_database_production
  pool: 5
  timeout: 5000
  template: template0