development:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/development.sqlite3
  
test:
  adapter: postgresql
  database: my_database_test
  pool: 5
  timeout: 5000
  template: template0

production:
  adapter: postgresql
  database: my_database_production
  pool: 5
  timeout: 5000
  template: template0
  
